language: ruby

rvm:
    - 2.0.0

script:
    - bundle exec rake db:migrate --trace
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake db:test:prepare
    - bundle exec rspec

deploy:

    provider: heroku

    api_key:

        secure: WJYjFbQ8lk/Kn4ThnNSAtrkYXiX6gnSrLNvdQf5RUST25ogS+imIH9p8B5B7\niJx/BO7sRo6d0GgjHCsA4pXj9XSyAAIZdQxnSh2TL7kzh0+yUWjahJJN8qcV\nsqUEX2Loe8ZdCbgQ6xdSo7nTVUuA2tPylfm9+fxb1vm5qdkB++w=

    run: rake db:migrate

notifications:

    email: false
